### ISSUE TITLE
Downloads only the first portion of data

### ISSUE THREAD

**Issue by andybat81** [Sensirion/myAmbienceManual#4]
I have a SHT40 connected with the app. I've been logging and downloading data since may.
Today I went to export and analyse the data, but the EDT file only contains the first 4/5 weeks worth of data.

**Comment by LeonieFierz** [comment]
Dear @andybat81 
thank you for contacting us. We know about the problem that the export currently does not work for a big amount of data. We are working on a bugfix to fix the problem, which should be public within the next weeks. Sorry for the inconvenience.
Best, Léonie

**Comment by LeonieFierz** [comment]
Dear @andybat81 
this Bug is now fixed with MyAmbience Version 3.4.1, published on Google Play and iOS AppStore.
Best, Léonie

**Comment by andybat81** [comment]
Hello @LeonieFierz .
Works like a charm. Thanks a lot!
